using Content.Client._WF.Stylesheets;
using Content.Shared._WF.PlanetCracker.Survey;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using RowData = Content.Shared._WF.PlanetCracker.Survey.BUI.WFSurveyPlanetRow;

namespace Content.Client._WF.PlanetCracker.Survey;

/// <summary>
/// One star-system body on the survey console: name, distance, the sanctioned/cracked/vein strip and the destination
/// line naming the body's own FTL beacon. The row carries no button and sends nothing anywhere - clicking it only
/// moves the window's client-local highlight.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WFSurveyPlanetRow : PanelContainer
{
    /// <summary>Raised when the crew clicks a row that resolves to a real body, for the client-local highlight only.</summary>
    public event Action<NetEntity>? OnClicked;

    /// <summary>The row's own panel box, rebuilt from the skin so selection can swap its background.</summary>
    private readonly StyleBoxFlat _panel;

    /// <summary>Background of an unselected row.</summary>
    private readonly Color _idleBackground;

    /// <summary>Background of the selected row.</summary>
    private readonly Color _selectedBackground;

    /// <summary>The body this row points at, or null when the star-system entry has no registered body.</summary>
    public NetEntity? Planet { get; }

    public WFSurveyPlanetRow(RowData data, WolfgateSkin skin)
    {
        RobustXamlLoader.Load(this);

        Planet = data.Planet;
        _idleBackground = skin.Glass;
        _selectedBackground = skin.Selection;

        _panel = new StyleBoxFlat
        {
            BackgroundColor = _idleBackground,
            BorderColor = skin.Edge,
            BorderThickness = new Thickness(2),
        };

        PanelOverride = _panel;

        // Clicks have to reach the row itself; the stock PanelContainer ignores them.
        MouseFilter = MouseFilterMode.Pass;

        NameLabel.Text = data.Name;
        NameLabel.FontColorOverride = data.HasSurface ? skin.Text : skin.AccentDim;

        DistanceLabel.Text = data.DistanceKnown
            ? Loc.GetString("wf-survey-row-distance", ("distance", (int)MathF.Round(data.Distance)))
            : Loc.GetString("wf-survey-row-distance-unknown");
        DistanceLabel.FontColorOverride = data.DistanceKnown ? skin.TextMuted : skin.TextDisabled;

        // A body with no surface prototype has no crackable ground at all, so it says that instead of a legal status.
        if (!data.HasSurface)
        {
            StatusSanctioned.Text = Loc.GetString("wf-survey-row-no-surface");
            StatusSanctioned.FontColorOverride = skin.AccentDim;
        }
        else
        {
            StatusSanctioned.Text = Loc.GetString(data.Sanctioned
                ? "wf-survey-row-sanctioned"
                : "wf-survey-row-unsanctioned");
            StatusSanctioned.FontColorOverride = data.Sanctioned ? skin.Good : skin.Caution;
        }

        StatusCracked.Text = Loc.GetString(data.Cracked ? "wf-survey-row-cracked" : "wf-survey-row-intact");
        StatusCracked.FontColorOverride = data.Cracked ? skin.Danger : skin.TextMuted;

        StatusVeins.Text = data.VeinsKnown
            ? Loc.GetString(RatingKey(data.Veins))
            : Loc.GetString("wf-survey-rating-unknown");
        StatusVeins.FontColorOverride = data.VeinsKnown ? skin.Accent : skin.TextDisabled;

        BeaconLabel.Text = data.HasBeacon
            ? Loc.GetString("wf-survey-row-beacon", ("beacon", data.Beacon))
            : Loc.GetString("wf-survey-row-beacon-none");
        BeaconLabel.FontColorOverride = data.HasBeacon ? skin.Accent : skin.TextDisabled;
    }

    /// <summary>Swaps the row's background between the skin's idle and selection colours.</summary>
    public void SetSelected(bool selected)
    {
        _panel.BackgroundColor = selected ? _selectedBackground : _idleBackground;
    }

    /// <inheritdoc/>
    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick || Planet is not { } planet)
            return;

        OnClicked?.Invoke(planet);
        args.Handle();
    }

    /// <summary>Locale key of a vein rating. The rating enum is the only vein information the state carries.</summary>
    private static string RatingKey(WFVeinRating rating)
    {
        return rating switch
        {
            WFVeinRating.VeryRich => "wf-survey-rating-very-rich",
            WFVeinRating.Rich => "wf-survey-rating-rich",
            WFVeinRating.Fair => "wf-survey-rating-fair",
            _ => "wf-survey-rating-poor",
        };
    }
}
