using Content.Client._WF.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CCVar;
using Content.Shared._WF.PlanetCracker.Survey.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._WF.PlanetCracker.Survey;

/// <summary>
/// The sector survey console: one row per star-system body, with its distance, legal status, crack state, vein rating
/// and the destination name a pilot types into the shuttle console. Everything comes out of one
/// <see cref="WFSurveyConsoleState"/>, and the only strings that are not locale keys are entity names that already
/// exist in the world. Nothing on this window sends a message; selection is a client-local highlight.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WFSurveyConsoleWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    /// <summary>The highlighted row, kept purely client-side; the server is never told which row anyone is reading.</summary>
    private NetEntity? _selected;

    public WFSurveyConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>Pushes one server state into every control on the window.</summary>
    public void UpdateState(WFSurveyConsoleState state)
    {
        // Re-read the skin each update so a mid-round style change takes effect on the next push.
        var skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));

        HeaderSystem.Text = Loc.GetString("wf-survey-console-system", ("system", state.SystemName));
        HeaderSystem.FontColorOverride = skin.Text;

        HeaderHint.Text = Loc.GetString("wf-survey-console-hint");
        HeaderHint.FontColorOverride = skin.TextMuted;

        PlanetCount.Text = Loc.GetString("wf-survey-console-count", ("count", state.Planets.Count));
        PlanetCount.FontColorOverride = skin.TextMuted;

        var empty = state.Planets.Count == 0;
        PlanetScroll.Visible = !empty;
        EmptyLabel.Visible = empty;
        EmptyLabel.Text = Loc.GetString("wf-survey-console-empty");
        EmptyLabel.FontColorOverride = skin.TextMuted;

        // Drop the highlight when the body it pointed at is no longer in the list.
        if (_selected is { } selected && !Contains(state, selected))
            _selected = null;

        Planets.RemoveAllChildren();

        foreach (var data in state.Planets)
        {
            var row = new WFSurveyPlanetRow(data, skin);
            row.SetSelected(data.Planet is { } planet && planet == _selected);
            row.OnClicked += OnRowClicked;
            Planets.AddChild(row);
        }
    }

    /// <summary>Moves the client-local highlight; clicking the selected row again clears it.</summary>
    private void OnRowClicked(NetEntity planet)
    {
        _selected = _selected == planet ? null : planet;

        foreach (var child in Planets.Children)
        {
            if (child is WFSurveyPlanetRow row)
                row.SetSelected(row.Planet is { } body && body == _selected);
        }
    }

    /// <summary>True when the state still carries a row for this body.</summary>
    private static bool Contains(WFSurveyConsoleState state, NetEntity planet)
    {
        foreach (var row in state.Planets)
        {
            if (row.Planet == planet)
                return true;
        }

        return false;
    }
}
