using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WF.PlanetCracker.Flight;

/// <summary>Asks before dropping a hull into an atmosphere it has not got the lift to climb back out of.</summary>
[GenerateTypedNameReferences]
public sealed partial class WFEnterAtmosphereConfirmWindow : FancyWindow
{
    /// <summary>The descent waiting for an answer. Cleared on every close, so an abort never sends it.</summary>
    private Action? _onConfirmed;

    public WFEnterAtmosphereConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        DescendButton.OnPressed += _ =>
        {
            var confirmed = _onConfirmed;
            Close();
            confirmed?.Invoke();
        };

        AbortButton.OnPressed += _ => Close();
        OnClose += () => _onConfirmed = null;
    }

    /// <summary>Opens the window for one descent, showing the lift the hull actually has.</summary>
    /// <param name="planet">The world below.</param>
    /// <param name="ratio">Lift over weight, as the server measured it.</param>
    /// <param name="onConfirmed">Runs only if the pilot presses through.</param>
    public void Ask(string planet, float ratio, Action onConfirmed)
    {
        _onConfirmed = onConfirmed;

        // The same bands the nav readout uses: climbable, sinking, falling.
        var colour = ratio >= 1f ? "#30ff30" : ratio >= 0.5f ? "#ffb030" : "#ff3030";

        WarningLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("wf-flight-confirm-text",
            ("planet", planet),
            ("ratio", ratio.ToString("F2")),
            ("colour", colour))));

        OpenCentered();
    }
}
