using Content.Client.UserInterface.Controls;
using Content.Shared._WF.PlanetCracker.Cracker;
using Content.Shared.Power;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WF.PlanetCracker.Cracker;

/// <summary>
/// The gravitic centrifuge's own machine window: the stock power switch and charge readouts driven by
/// <see cref="PowerChargeState"/>, plus the rotor dial.
/// The dial is fed from the networked <see cref="WFCentrifugeComponent"/> rather than from PowerChargeState, whose
/// Charge is quantised to a byte and only sent while the UI is open. This window's viewer is standing at the machine,
/// so the entity is always in PVS; feeding the dial the same four values the crack console gets keeps one dial
/// instead of two that disagree.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WFCentrifugeWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    /// <summary>The two power buttons behave as one switch.</summary>
    private readonly ButtonGroup _powerGroup = new();

    /// <summary>The machine whose component the dial reads.</summary>
    private EntityUid _owner;

    public WFCentrifugeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PowerOnButton.Group = _powerGroup;
        PowerOffButton.Group = _powerGroup;
    }

    /// <summary>Binds the window to its machine and its interface.</summary>
    public void SetOwner(WFCentrifugeBoundUserInterface bui, string title)
    {
        Title = title;
        _owner = bui.Owner;

        PowerOnButton.OnPressed += _ => bui.SetPowerSwitch(true);
        PowerOffButton.OnPressed += _ => bui.SetPowerSwitch(false);
    }

    /// <summary>Takes the switch and the charge readouts from the stock machine state.</summary>
    public void UpdateState(PowerChargeState state)
    {
        if (state.On)
            PowerOnButton.Pressed = true;
        else
            PowerOffButton.Pressed = true;

        ChargeStatusLabel.Text = Loc.GetString(state.PowerStatus switch
        {
            PowerChargePowerStatus.Off => "power-charge-window-status-off",
            PowerChargePowerStatus.Discharging => "power-charge-window-status-discharging",
            PowerChargePowerStatus.Charging => "power-charge-window-status-charging",
            _ => "power-charge-window-status-fully-charged",
        });

        ChargeStatusLabel.SetOnlyStyleClass(state.PowerStatus switch
        {
            PowerChargePowerStatus.Off => "Danger",
            PowerChargePowerStatus.Discharging or PowerChargePowerStatus.Charging => "Caution",
            _ => "Good",
        });

        ChargeEtaLabel.Text = state.EtaSeconds >= 0
            ? Loc.GetString("power-charge-window-eta-value", ("left", TimeSpan.FromSeconds(state.EtaSeconds)))
            : Loc.GetString("power-charge-window-eta-none");

        ChargeEtaLabel.SetOnlyStyleClass(state.EtaSeconds >= 0 ? "Caution" : "Disabled");
    }

    /// <inheritdoc/>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_entityManager.TryGetComponent(_owner, out WFCentrifugeComponent? centrifuge))
            return;

        RotorDial.SetReadout(centrifuge.Spin, centrifuge.AtFull, centrifuge.Load, centrifuge.Capacity);
    }
}
