using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._WF.Traders;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Traders;

/// <summary>
/// The used ship lot: whatever the salesman has bought back so far, and a button per hull.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TraderUsedShipsWindow : FancyWindow
{
    public event Action<int>? OnBuyPressed;

    public TraderUsedShipsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(TraderUsedShipsState state)
    {
        LotBox.RemoveAllChildren();

        if (state.Entries.Count == 0)
        {
            LotBox.AddChild(new Label
            {
                Text = Loc.GetString("trader-used-empty"),
                StyleClasses = { "LabelSecondaryColor" },
                Margin = new Robust.Shared.Maths.Thickness(4),
            });
        }

        foreach (var entry in state.Entries)
            LotBox.AddChild(MakeRow(entry));

        ZoneLabel.Text = Loc.GetString("trader-shop-zone-cash",
            ("amount", BankSystemExtensions.ToSpesoString(state.CashInZone)));
        BalanceLabel.Text = Loc.GetString("trader-shop-balance",
            ("amount", BankSystemExtensions.ToSpesoString(state.Balance)));
    }

    private BoxContainer MakeRow(TraderUsedShipEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        text.AddChild(new Label { Text = entry.ShipName, StyleClasses = { "LabelKeyText" } });
        text.AddChild(new Label
        {
            Text = Loc.GetString("trader-used-row-detail",
                ("design", entry.Design),
                ("seller", entry.Seller)),
            StyleClasses = { "LabelSecondaryColor" },
        });

        row.AddChild(text);
        row.AddChild(new Label
        {
            Text = BankSystemExtensions.ToSpesoString(entry.Price),
            Align = Label.AlignMode.Right,
            MinWidth = 90,
        });

        var buy = new Button
        {
            Text = Loc.GetString("trader-used-buy"),
            MinWidth = 80,
            StyleClasses = { "ButtonColorGreen" },
        };

        var id = entry.Id;
        buy.OnPressed += _ => OnBuyPressed?.Invoke(id);
        row.AddChild(buy);

        return row;
    }
}
