using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Utility;

namespace Content.Shared._WF.Wolfmed.Damage;

/// <summary>What the open wound on a limb looks like on the humanoid sprite (VISUALS).</summary>
[Serializable, NetSerializable]
public enum WolfmedWoundOverlay : byte
{
    None = 0,

    /// <summary>Still open but not bleeding: clotted, dressed, or a stump that has stopped.</summary>
    Old,

    /// <summary>Bleeding: a drip runs from the wound.</summary>
    Drip,

    /// <summary>Bleeding at or past wolfmed.wound_overlay_stream_rate: a steady trickle.</summary>
    Stream,
}

/// <summary>The wound and rot overlay art, and the RSI state each (layer, look) pair draws.</summary>
// The states are baked per part and per direction by Tools/_WF/Wolfmed/gen_wolfmed_overlays.py, so the layer map
// is the same ten layers the degradation overlay covers, with the same state prefixes.
public static class WolfmedWoundOverlays
{
    public static readonly ResPath WoundRsi = new("_WF/Wolfmed/Damage/wounds.rsi");
    public static readonly ResPath RotRsi = new("_WF/Wolfmed/Damage/rot.rsi");

    /// <summary>The wound state for one layer, or null for none or a layer with no art.</summary>
    public static string? GetWoundState(HumanoidVisualLayers layer, WolfmedWoundOverlay overlay)
    {
        var suffix = overlay switch
        {
            WolfmedWoundOverlay.Old => "old",
            WolfmedWoundOverlay.Drip => "drip",
            WolfmedWoundOverlay.Stream => "stream",
            _ => null,
        };
        return suffix != null && WolfmedDegradationLayers.TryGetPrefix(layer, out var prefix) ? $"{prefix}_{suffix}" : null;
    }

    /// <summary>The rot state for one layer, or null for a layer with no art. The chest state carries the groin too.</summary>
    public static string? GetRotState(HumanoidVisualLayers layer) =>
        WolfmedDegradationLayers.TryGetPrefix(layer, out var prefix) ? $"{prefix}_rot" : null;

    /// <summary>Which look wins when one layer has two parts behind it (a second left arm).</summary>
    public static int Rank(WolfmedWoundOverlay overlay) => (int) overlay;
}

/// <summary>
/// Per-species pixel shifts for the wound and rot overlays, which are drawn on the human silhouette. Generated by
/// Tools/_WF/Wolfmed/gen_overlay_offsets.py; a species or a layer missing from the table is not shifted.
/// </summary>
[Prototype("wolfmedOverlayOffsets")]
public sealed partial class WolfmedOverlayOffsetsPrototype : IPrototype
{
    public const string Default = "WFWolfmedOverlayOffsets";

    [IdDataField]
    public string ID { get; private set; } = default!;

    /// <summary>Species, then layer, to a shift in pixels, up and right positive. Applied in every direction.</summary>
    [DataField]
    public Dictionary<ProtoId<SpeciesPrototype>, Dictionary<HumanoidVisualLayers, Vector2i>> Species = new();

    /// <summary>The shift for one species' layer, zero when the table has none.</summary>
    public Vector2i Get(ProtoId<SpeciesPrototype> species, HumanoidVisualLayers layer) =>
        Species.TryGetValue(species, out var layers) && layers.TryGetValue(layer, out var offset)
            ? offset
            : Vector2i.Zero;
}
